include: package:flutter_lints/flutter.yaml

linter:
  rules:
    omit_local_variable_types: false
    avoid_print: false
    prefer_final_fields: true
    prefer_const_constructors_in_immutables: false
