include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/gen/**.dart
    - test/**.mocks.dart
  errors:
    invalid_use_of_visible_for_testing_member: error
    null_check_on_nullable_type_parameter: error
    prefer_typing_uninitialized_variables: error
    tighten_type_of_initializing_formals: error
    collection_methods_unrelated_type: error
    use_build_context_synchronously: error
    unrelated_type_equality_checks: error
    conditional_uri_does_not_exist: error
    prefer_null_aware_method_calls: error
    cast_nullable_to_non_nullable: error
    prefer_null_aware_operators: error
    missing_required_param: error
    await_only_futures: error
    recursive_getters: error
    missing_return: error
    null_closures: error
    avoid_equals_and_hash_code_on_mutable_classes: warning
    avoid_null_checks_in_equality_operators: warning
    prefer_for_elements_to_map_fromIterable: warning
    use_full_hex_values_for_flutter_colors: warning
    avoid_shadowing_type_parameters: warning
    avoid_annotating_with_dynamic: warning
    no_duplicate_case_values: warning
    no_runtimeType_toString: warning
    avoid_catching_errors: warning
    parameter_assignments: warning
    avoid_js_rounded_ints: warning
    cancel_subscriptions: warning
    test_types_in_equals: warning
    prefer_is_not_empty: warning
    avoid_slow_async_io: warning
    use_string_buffers: warning
    only_throw_errors: warning
    unawaited_futures: warning
    avoid_void_async: warning
    exhaustive_cases: warning
    hash_and_equals: warning
    prefer_contains: warning
    prefer_is_empty: warning
    close_sinks: warning
    use_enums: warning
    avoid_positional_boolean_parameters: ignore
    invalid_annotation_target: ignore
    type_annotate_public_apis: ignore
    
linter:
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - collection_methods_unrelated_type
    - empty_statements
    - hash_and_equals
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    - always_declare_return_types
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - conditional_uri_does_not_exist
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - implementation_imports
    - implicit_call_tearoffs
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_runtimeType_toString
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - require_trailing_commas
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - use_enums
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - void_checks
    - avoid_print
    - avoid_web_libraries_in_flutter
    - avoid_unnecessary_containers
    - no_logic_in_create_state
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - avoid_function_literals_in_foreach_calls
    - avoid_js_rounded_ints
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - sort_child_properties_last
    - use_colored_box
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - flutter_style_todos