name: cv_online_v2
description: CV en ligne de DEVILLIERS Matthieu

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.10.1+27

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: 4.2.1
  cloud_firestore: 3.1.16
  equatable: 2.0.3
  firebase_auth: 3.3.18
  firebase_core: 1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: 10.1.0
  intl: 0.17.0
  package_info_plus: 1.4.2
  shared_preferences: 2.0.15
  url_launcher: 6.1.2
  url_strategy: 0.2.0

dev_dependencies:
  flutter_native_splash: 2.2.1
  flutter_test:
    sdk: flutter
  lint: 1.8.2

flutter_native_splash:
  color: "#121212"
  image: assets/images/512px-Google_Assistant_logo.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Regular.ttf
