name: cv_online_v2
description: CV en ligne de DEVILLIERS Matthieu

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.11.0+28

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^4.3.1
  collection: ^1.16.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter: { sdk: flutter }
  flutter_localizations: { sdk: flutter }
  font_awesome_flutter: ^10.3.0
  intl: ^0.17.0
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_native_splash: ^2.2.16
  flutter_test: { sdk: flutter }
  flutter_lints: ^2.0.1

flutter_native_splash:
  color: "#121212"
  image: assets/images/512px-Google_Assistant_logo.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Regular.ttf
