name: cv_online_v2
description: CV en ligne de DEVILLIERS Matthieu

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.8.1+18

environment:
  sdk: ">=2.12.0 <3.0.0"
  version: "2.5.3"

dependencies:
  animated_text_kit: ^4.2.1
  bloc: ^7.2.1
  cloud_firestore: ^2.5.4
  firebase_analytics: ^8.3.4
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.4
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.9
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter_native_splash:
  color: "#121212"
  image: images/512px-Google_Assistant_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/l10n/
    - assets/images/
    - assets/images/project/

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Regular.ttf
