name: cv_online_v2
description: CV en ligne de DEVILLIERS Matthieu

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.14.1+32

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.3
  cloud_firestore: ^5.6.6
  collection: ^1.19.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter: { sdk: flutter }
  flutter_localizations: { sdk: flutter }
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_native_splash: ^2.4.4 # dart run flutter_native_splash:create
  flutter_test: { sdk: flutter }
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#121212"
  image: assets/images/512px-Google_Assistant_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/l10n/

  fonts:
    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Regular.ttf
