name: cv_online_v2
description: CV en ligne de DEVILLIERS Matthieu

publish_to: "none"

version: 0.5.2+9

environment:
  sdk: ">=2.12.0 <3.0.0"
  version: "2.2.3"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  url_launcher: ^6.0.9
  intl: ^0.17.0
  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/project/

  fonts:
    - family: KaushanScript
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-Italic.ttf
          style: italic
        - asset: fonts/Raleway-Regular.ttf
