# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.3"
          channel: "stable"
          cache: true
          cache-key: flutter 2.10.3 # change this to force refresh cache
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter doctor -v
      - run: flutter analyze
